services:
  app:
    build:
      context: .
    container_name: cashback-app
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      - DB_PATH=/data/cashback.db
    volumes:
      - ./data:/data
      - ./uploads:/app/uploads

volumes: {}